### PR TITLE
148

### PR DESCRIPTION
**Pull request by JohanMabille**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by JohanMabille** [comment]
@jaimergp sorry for the late repy, I've checked it and I'm trying to reproduce the issue, unsuccessfully for the moment :s

**Comment by jaimergp** [comment]
I can reproduce like this:

1. Run the mambaforge image from condaforge:

```bash
$ docker run -it --rm --platform=linux/amd64 condaforge/mambaforge:latest bash
```

2. Inside the container, run:


```bash
$ mamba update --all -y
$ conda install https://anaconda.org/conda-forge/mamba/1.4.8/download/linux-64/mamba-1.4.8-py310h51d5547_0.conda
$ mamba update --all -y  # we need to do it like this because 1.4.8 is marked as broken now
$ mamba install "python==3.9.*" pip cerberus tornado xonsh==0.9.24 zict tqdm toolz jinja2 lazyasd pandas networkx requests ruamel_yaml wget conda-package-streaming
```

The error will show up after finishing the downloads of the packages in the last command.

**Comment by JohanMabille** [comment]
@jaimergp thanks, I finally did the same, and then managed to get a smaller reproducer without the docker image, see https://github.com/mamba-org/mamba/issues/2665#issuecomment-1631523424

I am now tracking it :smiling_imp:

**Comment by jaimergp** [comment]
Nice, thanks for tracking it!

**Pull request merged**
