### PR TITLE
Pin to conda <23.9.0

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR acts as a workaround for https://github.com/mamba-org/mamba/issues/2882 until https://github.com/mamba-org/mamba/pull/2878 is be released, by pinning the `mamba` package to `conda <23.9.0a0`.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
Presumably, a repopatch will also be needed for build 0?

**Comment by duncanmmacleod** [comment]
@xylar, I suppose a repo patch would be the best solution all-around, to not create a secondary build - however this was the easiest thing I could think of this morning. I can propose one of those as an alternative.

**Comment by duncanmmacleod** [comment]
Actually, looks like I was beaten to it, see https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/563. ATOW this hasn't propagated yet, but should do soon.

**Comment by xylar** [comment]
> @xylar, I suppose a repo patch would be the best solution all-around, to not create a secondary build - however this was the easiest thing I could think of this morning. I can propose one of those as an alternative.

This should still be merged.  We don't want future builds of this version of `mamba` (if there are any) to propagate the problem.

**Comment by xylar** [comment]
Hey @conda-forge/mamba maintainers, is there a page somewhere that discusses the strategy for constraining the `conda` version that a given `mamba` release supports?  It's been a pretty big pain for me and the folks I work with when a new conda release breaks mamba.  I figure here isn't really the place to discuss this but I didn't find anywhere on the `mamba` upstream repo where conda is actually constrained so wanted to know if that's a decision made here or somewhere else.

It seems to me that recent experience suggests that new conda releases break mamba often enough that the default should be that unrelease conda versions are *not* supported and that new builds of `mamba` could be made here to loosen the constraints after it is clear that they are compatible.

**Pull request merged**
