### PR TITLE
Release 1.5.5

### PR DESCRIPTION
**Pull request by JohanMabille**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mbargull** [comment]
@JohanMabille, could you merge gh-205 into this?

**Comment by JohanMabille** [comment]
arrrgh it fails :(

**Comment by mbargull** [comment]
> arrrgh it fails :(

You mean my draft PR?
Yes, it was supposed to since it ran with `1.5.4` :).
Once it runs with `1.5.5` (hence my ask to merge it here), it should run through.

**Comment by JohanMabille** [comment]
> Yes, it was supposed to since it ran with 1.5.4 :).

I think I need some sleep :face_with_spiral_eyes:

**Pull request merged**
