### PR TITLE
v0.3.7

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
hehe thanks for opening the PR. 
I was lazy & waiting for the bot to appear (also I was afk before, so sorry I didn't do this sooner).

**Comment by marcelotrevisani** [comment]
> hehe thanks for opening the PR.
> I was lazy & waiting for the bot to appear (also I was afk before, so sorry I didn't do this sooner).

No worries! I just would like to use it as soon as possible :smile:

**Comment by marcelotrevisani** [comment]
Funny thing, I think I found a bug on azure, one of the jobs is appearing as it started 16hours ago LOL
image

**Pull request merged**
