### PR TITLE
MNT: rerender

### LINKED ISSUE #153: @conda-forge-admin rerender
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #153.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #153

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@wolfv this one too

**Comment by wolfv** [comment]
I was planning to make a repodata patch otherwise. Or we could move build 0 to broken and merge this one. What do you think?

**Comment by beckermr** [comment]
Either way. Right now automerge is on so remove that if you want to not merge this.

**Comment by wolfv** [comment]
the repodata patch has fixed this. Thanks @beckermr for fixing the compilers!!

**Pull request closed without merging**
