### PR TITLE
Test with pip check

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
Thanks @wolfv for fixing #109! :pray:  In order to have it recognized by conda-forge, it needs to come from a GitHub release.

Once that release happens, I should be able to update and merge this. (I have already set myself a release notification on mamba.)

**Comment by maresb** [comment]
I rebased on autotickbot's commit

**Comment by wolfv** [comment]
looks good! thanks!

**Comment by maresb** [comment]
I'm not sure why Travis CI is giving the red X. Everything looks good to me. Does it just mean "awaiting review"?

**Comment by maresb** [comment]
I'd appreciate if we could merge this. I'm starting to get annoyed by all the rebasing. :wink:

**Comment by wolfv** [comment]
yep, thanks! sorry :)

**Pull request merged**
